/**
 * CraveCompass — Comprehensive Dhaka, Bangladesh Seed Script
 * Pre-populates MongoDB with 46 authentic, curated restaurants across Dhaka:
 * Gulshan, Banani, Dhanmondi, Old Dhaka (Puran Dhaka), Uttara, Khilgaon, Baily Road, Mirpur.
 *
 * Cuisines: Pizza, Burgers, Biryani, Kabab, Bangladeshi, Chicken, Coffee/Cafes,
 * Sushi/Japanese, Thai/Asian, Seafood, Breakfast/Brunch, Desserts.
 *
 * Run: npm run seed
 */
require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const Place = require('../models/Place');

const SEED_PLACES = [
  // ── DHANMONDI ──────────────────────────────────────────────────
  {
    googlePlaceId: 'seed_dhaka_001',
    name: 'Kacchi Bhai',
    location: { type: 'Point', coordinates: [90.3742, 23.7461] },
    address: {
      formatted: 'Road 4, Dhanmondi, Dhaka 1205',
      street: 'Road 4',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1205',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 2,
    rating: 4.7,
    totalRatings: 8420,
    phone: '+880 1711-234567',
    website: 'https://kacchibhai.com',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    tags: ['kacchi biryani', 'mutton', 'bangladeshi', 'popular', 'dhanmondi', 'must-try', 'borhani'],
    reviews: [
      { author: 'Rahim Ahmed', rating: 5, text: 'Best kacchi biryani in Dhaka! Tender mutton and fragrant chinigura rice.' },
      { author: 'Nusrat Jahan', rating: 5, text: 'A Dhaka institution. Always consistent quality, worth every taka.' },
    ],
    popularityScore: 1200,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_004',
    name: 'Fakruddin Biryani House',
    location: { type: 'Point', coordinates: [90.3780, 23.7500] },
    address: {
      formatted: 'House 6, Road 7/A, Dhanmondi, Dhaka 1209',
      street: 'Road 7/A',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1209',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 2,
    rating: 4.6,
    totalRatings: 5800,
    phone: '+880 1813-567890',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1624374053855-39404ebda88b?w=800&q=80',
    tags: ['biryani', 'tehari', 'dhanmondi', 'bangladeshi', 'family', 'takeaway'],
    reviews: [
      { author: 'Tanvir Ahmed', rating: 5, text: 'Fakruddin biryani is iconic! Perfectly spiced, generous portions.' },
      { author: 'Riya Chowdhury', rating: 4, text: 'Best beef tehari in the city. Always reliable quality.' },
    ],
    popularityScore: 1050,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_012',
    name: 'Moshla Kitchen',
    location: { type: 'Point', coordinates: [90.3760, 23.7520] },
    address: {
      formatted: 'House 5, Road 27, Dhanmondi, Dhaka 1209',
      street: 'Road 27',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1209',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'indian'],
    priceLevel: 2,
    rating: 4.6,
    totalRatings: 2100,
    phone: '+880 1855-345678',
    openingHours: {
      openNow: false,
      weekdayText: ['Daily: 12:00 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=800&q=80',
    tags: ['bangladeshi', 'curry', 'dhanmondi', 'modern', 'spicy', 'family', 'desi'],
    reviews: [
      { author: 'Joyita Dey', rating: 5, text: 'Modern take on traditional Bangladeshi cuisine. Flavor bomb!' },
      { author: 'Wasim Akram', rating: 4, text: 'Great curries, very authentic. The chicken rezala is superb.' },
    ],
    popularityScore: 760,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_014',
    name: 'Cheez Dhaka',
    location: { type: 'Point', coordinates: [90.3755, 23.7510] },
    address: {
      formatted: 'House 34, Road 27, Dhanmondi, Dhaka 1209',
      street: 'Road 27',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1209',
    },
    categories: ['restaurant', 'pizza_restaurant'],
    cuisine: ['pizza', 'fast food'],
    priceLevel: 2,
    rating: 4.5,
    totalRatings: 2600,
    phone: '+880 1833-445566',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:30 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
    tags: ['pizza', 'deep dish', 'cheese pull', 'dhanmondi', 'casual', 'slice', 'pepperoni'],
    reviews: [
      { author: 'Fahim Reza', rating: 5, text: 'The cheese pull on their deep dish pizza is unreal! Cozy vibe.' },
      { author: 'Afreen Noor', rating: 4, text: 'Great cheesy pizza at affordable prices. Loved the garlic bread.' },
    ],
    popularityScore: 890,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_017',
    name: 'Takeout Dhanmondi',
    location: { type: 'Point', coordinates: [90.3770, 23.7480] },
    address: {
      formatted: 'House 7A, Road 5, Dhanmondi, Dhaka 1205',
      street: 'Road 5',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1205',
    },
    categories: ['restaurant', 'burger_restaurant', 'fast_food'],
    cuisine: ['burger', 'american', 'fast food'],
    priceLevel: 2,
    rating: 4.6,
    totalRatings: 6300,
    phone: '+880 1722-334455',
    website: 'https://takeoutbd.com',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
    tags: ['burger', 'beef burger', 'cheese burger', 'dhanmondi', 'popular', 'fries', 'iconic'],
    reviews: [
      { author: 'Mahir Faisal', rating: 5, text: 'Pioneer of Dhaka burger culture! Juiciest beef patties in town.' },
      { author: 'Tasnim Zahid', rating: 4, text: 'Classic Beef Cheese Burger with extra sauce is unbeatable.' },
    ],
    popularityScore: 1150,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_018',
    name: 'Sultan\'s Dine',
    location: { type: 'Point', coordinates: [90.3750, 23.7495] },
    address: {
      formatted: 'Green Akshay Plaza, Road 9A, Dhanmondi, Dhaka 1209',
      street: 'Road 9A',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1209',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 2,
    rating: 4.8,
    totalRatings: 9100,
    phone: '+880 1713-112233',
    website: 'https://sultansdine.com',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    tags: ['kacchi biryani', 'sultans dine', 'dhanmondi', 'mutton', 'borhani', 'legendary'],
    reviews: [
      { author: 'Alvi Hassan', rating: 5, text: 'The gold standard for Kacchi Biryani in Bangladesh. Tender mutton, aromatic rice, best borhani.' },
      { author: 'Mahi Chowdhury', rating: 5, text: 'Incredible flavor and massive portions. Always a 10/10 feast!' },
    ],
    popularityScore: 1350,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_031',
    name: 'Bar-B-Q Tonight Dhaka',
    location: { type: 'Point', coordinates: [90.3758, 23.7535] },
    address: {
      formatted: 'Road 27, House 42, Dhanmondi, Dhaka 1209',
      street: 'Road 27',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1209',
    },
    categories: ['restaurant', 'barbecue_restaurant'],
    cuisine: ['kabab', 'mughlai', 'chicken'],
    priceLevel: 3,
    rating: 4.5,
    totalRatings: 3200,
    phone: '+880 1711-889977',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:30 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    tags: ['kabab', 'reshmi kabab', 'mutton chops', 'dhanmondi', 'bbq', 'family dining'],
    reviews: [
      { author: 'Sohail Tanvir', rating: 5, text: 'Best mutton ribs and reshmi kabab in Dhaka! Fresh hot rogni naan.' },
      { author: 'Farhana Haque', rating: 4, text: 'Always a top choice for barbecue with family. High quality.' },
    ],
    popularityScore: 890,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_032',
    name: 'Crimson Cup Coffee House',
    location: { type: 'Point', coordinates: [90.3768, 23.7525] },
    address: {
      formatted: 'Road 27, Dhanmondi, Dhaka 1209',
      street: 'Road 27',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1209',
    },
    categories: ['cafe', 'coffee_shop'],
    cuisine: ['coffee', 'breakfast', 'dessert'],
    priceLevel: 2,
    rating: 4.6,
    totalRatings: 4100,
    phone: '+880 1788-223344',
    website: 'https://crimsoncup.com.bd',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 8:00 AM – 12:00 AM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80',
    tags: ['coffee', 'mocha', 'dhanmondi', 'wifi', 'cozy', 'study cafe', 'cheesecake'],
    reviews: [
      { author: 'Anika Bushra', rating: 5, text: 'Cozy study environment and rich iced caramel macchiato. My everyday hangout.' },
      { author: 'Zubair Hossain', rating: 4, text: 'Great coffee aroma and fast wifi. Friendly baristas.' },
    ],
    popularityScore: 920,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_033',
    name: 'Madchef Dhanmondi',
    location: { type: 'Point', coordinates: [90.3735, 23.7485] },
    address: {
      formatted: 'Shimanto Square, Road 2, Dhanmondi, Dhaka 1205',
      street: 'Road 2',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1205',
    },
    categories: ['restaurant', 'burger_restaurant'],
    cuisine: ['burger', 'american', 'fast food'],
    priceLevel: 2,
    rating: 4.5,
    totalRatings: 3700,
    phone: '+880 1922-334411',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    tags: ['burger', 'gourmet burger', 'dhanmondi', 'fries', 'milkshakes', 'cheddar'],
    reviews: [
      { author: 'Nafis Iqbal', rating: 5, text: 'Dhaka Dhabba burger is top tier! Thick juicy patty and spicy mayo.' },
      { author: 'Sumaiya Binte', rating: 4, text: 'Very consistent gourmet burgers. Love the poutine fries.' },
    ],
    popularityScore: 880,
    isFeatured: false,
    source: 'seed',
  },

  // ── BANANI & MOHAKHALI ─────────────────────────────────────────
  {
    googlePlaceId: 'seed_dhaka_006',
    name: 'Chillox Banani',
    location: { type: 'Point', coordinates: [90.4046, 23.7937] },
    address: {
      formatted: 'Road 11, Block C, Banani, Dhaka 1213',
      street: 'Road 11',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1213',
    },
    categories: ['restaurant', 'burger_restaurant', 'fast_food'],
    cuisine: ['burger', 'american', 'fast food'],
    priceLevel: 2,
    rating: 4.5,
    totalRatings: 4700,
    phone: '+880 1700-789012',
    website: 'https://chillox.com.bd',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:00 AM – 12:00 AM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    tags: ['burger', 'smash burger', 'banani', 'trendy', 'halal', 'late night', 'takeaway'],
    reviews: [
      { author: 'Adnan Siddiqui', rating: 5, text: 'Hands down the best burgers in Dhaka! The smash burger is insane.' },
      { author: 'Priya Das', rating: 4, text: 'Great burger spot. Highly recommend the Chillox Special with sausage.' },
    ],
    popularityScore: 920,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_010',
    name: 'Café Mango',
    location: { type: 'Point', coordinates: [90.4020, 23.7700] },
    address: {
      formatted: 'DOHS, Road 2, Mohakhali, Dhaka 1206',
      street: 'Road 2, DOHS',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1206',
    },
    categories: ['cafe', 'restaurant'],
    cuisine: ['coffee', 'breakfast', 'continental'],
    priceLevel: 2,
    rating: 4.5,
    totalRatings: 2800,
    phone: '+880 1677-123456',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 8:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    tags: ['coffee', 'brunch', 'cafe', 'continental', 'wifi', 'casual', 'mohakhali', 'dessert'],
    reviews: [
      { author: 'Nadia Hossain', rating: 5, text: 'Cozy atmosphere, great coffee, and reliable wifi for working.' },
      { author: 'Arif Khan', rating: 4, text: 'Lovely brunch spot. The pasta and latte are both excellent.' },
    ],
    popularityScore: 840,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_011',
    name: 'Butcher\'s Burger',
    location: { type: 'Point', coordinates: [90.4075, 23.7960] },
    address: {
      formatted: 'House 28, Road 17, Banani, Dhaka 1213',
      street: 'Road 17',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1213',
    },
    categories: ['restaurant', 'burger_restaurant'],
    cuisine: ['burger', 'american'],
    priceLevel: 3,
    rating: 4.5,
    totalRatings: 3400,
    phone: '+880 1944-234567',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&q=80',
    tags: ['burger', 'beef burger', 'banani', 'premium', 'halal', 'trendy'],
    reviews: [
      { author: 'Shahriar Hossain', rating: 5, text: 'Premium burgers with quality beef. Worth every taka!' },
      { author: 'Asha Roy', rating: 4, text: 'Excellent burgers and great fries. One of the top burger spots.' },
    ],
    popularityScore: 870,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_013',
    name: 'Pizza Guy Banani',
    location: { type: 'Point', coordinates: [90.4062, 23.7942] },
    address: {
      formatted: 'Road 11, Block D, Banani, Dhaka 1213',
      street: 'Road 11',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1213',
    },
    categories: ['restaurant', 'pizza_restaurant', 'italian_restaurant'],
    cuisine: ['pizza', 'italian'],
    priceLevel: 3,
    rating: 4.7,
    totalRatings: 3100,
    phone: '+880 1788-990011',
    website: 'https://pizzaguybd.com',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
    tags: ['pizza', 'wood fired pizza', 'sourdough', 'banani', 'italian', 'popular', 'cheese', 'margherita'],
    reviews: [
      { author: 'Tanvir Rahman', rating: 5, text: 'Best wood-fired pizza in Dhaka! Authentic sourdough crust.' },
      { author: 'Samira Anjum', rating: 5, text: 'Pepperoni and truffle pizza are incredible. Must-visit in Banani.' },
    ],
    popularityScore: 980,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_025',
    name: 'Tokyo Express Banani',
    location: { type: 'Point', coordinates: [90.4035, 23.7930] },
    address: {
      formatted: 'Road 11, House 67, Banani, Dhaka 1213',
      street: 'Road 11',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1213',
    },
    categories: ['restaurant', 'japanese_restaurant'],
    cuisine: ['sushi', 'japanese'],
    priceLevel: 3,
    rating: 4.4,
    totalRatings: 2200,
    phone: '+880 1755-443322',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:30 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80',
    tags: ['sushi', 'ramen', 'bento', 'banani', 'japanese', 'california roll', 'tempura'],
    reviews: [
      { author: 'Mehedi Hasan', rating: 5, text: 'Super fresh salmon nigiri and spicy tuna rolls! Cozy ambiance.' },
      { author: 'Nadia Karim', rating: 4, text: 'Authentic ramen broth and crispy prawn tempura. Highly recommended.' },
    ],
    popularityScore: 790,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_026',
    name: 'North End Coffee Roasters Banani',
    location: { type: 'Point', coordinates: [90.4050, 23.7920] },
    address: {
      formatted: 'Road 11, Banani, Dhaka 1213',
      street: 'Road 11',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1213',
    },
    categories: ['cafe', 'coffee_shop'],
    cuisine: ['coffee', 'breakfast', 'dessert'],
    priceLevel: 2,
    rating: 4.8,
    totalRatings: 5200,
    phone: '+880 1711-556677',
    website: 'https://northendcoffee.com',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 7:30 AM – 11:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    tags: ['coffee', 'espresso', 'cappuccino', 'banani', 'artisan', 'croissant', 'cinnamon roll'],
    reviews: [
      { author: 'Shafiqul Alam', rating: 5, text: 'The pioneer of specialty coffee in Bangladesh. Freshly roasted beans!' },
      { author: 'Rasheda Parvin', rating: 5, text: 'Their iced Americano and cinnamon roll are heavenly.' },
    ],
    popularityScore: 1100,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_027',
    name: 'The Manhattan FISH MARKET',
    location: { type: 'Point', coordinates: [90.4080, 23.7915] },
    address: {
      formatted: 'Road 11, Block D, Banani, Dhaka 1213',
      street: 'Road 11',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1213',
    },
    categories: ['restaurant', 'seafood_restaurant'],
    cuisine: ['seafood', 'american'],
    priceLevel: 3,
    rating: 4.4,
    totalRatings: 2900,
    phone: '+880 1844-332211',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&q=80',
    tags: ['seafood', 'fish and chips', 'flaming platter', 'prawns', 'banani', 'calamari'],
    reviews: [
      { author: 'Arman Khan', rating: 5, text: 'The Manhattan Flaming Seafood Platter is a showstopper and delicious!' },
      { author: 'Maliha Rahman', rating: 4, text: 'Crispy batter fish and garlic herb rice. Great family seafood feast.' },
    ],
    popularityScore: 810,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_028',
    name: 'Yum Cha District Banani',
    location: { type: 'Point', coordinates: [90.4042, 23.7948] },
    address: {
      formatted: 'House 55, Road 11, Banani, Dhaka 1213',
      street: 'Road 11',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1213',
    },
    categories: ['restaurant', 'asian_restaurant'],
    cuisine: ['chinese', 'thai', 'asian'],
    priceLevel: 3,
    rating: 4.5,
    totalRatings: 2100,
    phone: '+880 1777-665544',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&q=80',
    tags: ['dim sum', 'dumplings', 'bao bun', 'banani', 'asian street food', 'noodles'],
    reviews: [
      { author: 'Sabrina Mostafa', rating: 5, text: 'Authentic soup dumplings (Xiao Long Bao) and spicy dan dan noodles!' },
      { author: 'Tareq Aziz', rating: 4, text: 'Crispy duck bao and prawn har gow are stellar.' },
    ],
    popularityScore: 780,
    isFeatured: false,
    source: 'seed',
  },

  // ── GULSHAN 1 & 2 ──────────────────────────────────────────────
  {
    googlePlaceId: 'seed_dhaka_005',
    name: 'Nando\'s Gulshan',
    location: { type: 'Point', coordinates: [90.4138, 23.7905] },
    address: {
      formatted: 'Gulshan Avenue, Plot 104, Gulshan 2, Dhaka 1212',
      street: 'Gulshan Avenue',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'fast_food', 'chicken_restaurant'],
    cuisine: ['american', 'chicken'],
    priceLevel: 3,
    rating: 4.3,
    totalRatings: 3200,
    phone: '+880 1988-678901',
    website: 'https://nandos.com.bd',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1598514982901-e51c3b664b72?w=800&q=80',
    tags: ['peri peri', 'chicken', 'gulshan', 'flame grilled', 'wings', 'halal'],
    reviews: [
      { author: 'Zara Khan', rating: 4, text: 'Great peri-peri chicken as always! Gulshan branch has great ambiance.' },
      { author: 'Sahil Rahman', rating: 4, text: 'Consistently good food and service. Love the extra hot wings.' },
    ],
    popularityScore: 780,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_007',
    name: 'Izumi Japanese Restaurant',
    location: { type: 'Point', coordinates: [90.4148, 23.7820] },
    address: {
      formatted: 'CWS-A 8, Gulshan North Avenue, Gulshan 1, Dhaka 1212',
      street: 'Gulshan North Avenue',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'japanese_restaurant'],
    cuisine: ['sushi', 'japanese'],
    priceLevel: 4,
    rating: 4.6,
    totalRatings: 1800,
    phone: '+880 1755-890123',
    openingHours: {
      openNow: false,
      weekdayText: ['Daily: 12:00 PM – 3:00 PM, 7:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    tags: ['sushi', 'sashimi', 'japanese', 'gulshan', 'fine dining', 'upscale', 'date night'],
    reviews: [
      { author: 'Mehnaz Parveen', rating: 5, text: 'Best Japanese food in Dhaka! Beautiful garden courtyard.' },
      { author: 'Imran Chowdhury', rating: 5, text: 'The sashimi grade tuna and salmon are fresh flown-in quality.' },
    ],
    popularityScore: 720,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_008',
    name: 'Thai Garden Restaurant',
    location: { type: 'Point', coordinates: [90.4120, 23.7860] },
    address: {
      formatted: 'House 43, Road 113, Gulshan 2, Dhaka 1212',
      street: 'Road 113',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'thai_restaurant'],
    cuisine: ['thai', 'asian'],
    priceLevel: 3,
    rating: 4.4,
    totalRatings: 1500,
    phone: '+880 1822-901234',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800&q=80',
    tags: ['thai', 'pad thai', 'tom yum', 'gulshan', 'upscale', 'green curry'],
    reviews: [
      { author: 'Luna Akter', rating: 4, text: 'Authentic Thai flavors in Gulshan. Great tom yum soup!' },
      { author: 'Reza Islam', rating: 5, text: 'The green curry and sticky mango rice are unbeatable.' },
    ],
    popularityScore: 680,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_015',
    name: 'Pizza Hut Gulshan 1',
    location: { type: 'Point', coordinates: [90.4150, 23.7800] },
    address: {
      formatted: 'Plot 15, Gulshan Avenue, Gulshan 1, Dhaka 1212',
      street: 'Gulshan Avenue',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'pizza_restaurant'],
    cuisine: ['pizza', 'american'],
    priceLevel: 2,
    rating: 4.3,
    totalRatings: 4900,
    phone: '+880 1977-889900',
    website: 'https://pizzahutbd.com',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80',
    tags: ['pizza', 'pan pizza', 'stuffed crust', 'gulshan', 'family', 'wings'],
    reviews: [
      { author: 'Nazmul Haque', rating: 4, text: 'Classic stuffed crust pan pizza. Reliable family dinner spot.' },
      { author: 'Rashedul Karim', rating: 4, text: 'Fast service. The beef supreme and garlic bread are great.' },
    ],
    popularityScore: 850,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_016',
    name: 'Bella Italia Gulshan',
    location: { type: 'Point', coordinates: [90.4180, 23.7910] },
    address: {
      formatted: 'Road 50, Gulshan 2, Dhaka 1212',
      street: 'Road 50',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'italian_restaurant', 'pizza_restaurant'],
    cuisine: ['pizza', 'italian'],
    priceLevel: 4,
    rating: 4.6,
    totalRatings: 1400,
    phone: '+880 1711-002233',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800&q=80',
    tags: ['pizza', 'italian', 'wood fired', 'pasta', 'gulshan', 'fine dining', 'date night'],
    reviews: [
      { author: 'Sadik Rahman', rating: 5, text: 'Authentic Italian pizza with crispy thin crust and rich mozzarella.' },
      { author: 'Nayla Kabir', rating: 5, text: 'Romantic ambiance, great tiramisu and wood-fired quattro formaggi.' },
    ],
    popularityScore: 820,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_023',
    name: 'Farmhouse Burger Gulshan',
    location: { type: 'Point', coordinates: [90.4165, 23.7925] },
    address: {
      formatted: 'House 12, Road 53, Gulshan 2, Dhaka 1212',
      street: 'Road 53',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'burger_restaurant'],
    cuisine: ['burger', 'american'],
    priceLevel: 3,
    rating: 4.7,
    totalRatings: 3800,
    phone: '+880 1733-445588',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&q=80',
    tags: ['burger', 'smash burger', 'brioche bun', 'gulshan', 'artisanal', 'truffle fries'],
    reviews: [
      { author: 'Raihan Siddiq', rating: 5, text: 'Best artisanal smash burgers in Gulshan. The brioche bun is pillowy soft.' },
      { author: 'Farzeen Huq', rating: 5, text: 'Truffle mushroom burger and sweet potato fries are unmissable.' },
    ],
    popularityScore: 990,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_024',
    name: 'Prego at The Westin Dhaka',
    location: { type: 'Point', coordinates: [90.4132, 23.7918] },
    address: {
      formatted: 'Plot 1, CWN(B), Road 45, Gulshan 2, Dhaka 1212',
      street: 'Road 45',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'italian_restaurant', 'pizza_restaurant'],
    cuisine: ['pizza', 'italian'],
    priceLevel: 4,
    rating: 4.7,
    totalRatings: 1800,
    phone: '+880 2-9891988',
    openingHours: {
      openNow: false,
      weekdayText: ['Daily: 6:30 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=800&q=80',
    tags: ['pizza', 'fine dining', 'the westin', 'gulshan', 'italian', 'wood fired oven', 'skyline view'],
    reviews: [
      { author: 'Kazi Mahbub', rating: 5, text: 'Top floor Italian dining with panoramic skyline views of Dhaka. World class pizza.' },
      { author: 'Eshita Zaman', rating: 5, text: 'Exceptional wine pairing, freshly baked focaccia and wood fired pizza.' },
    ],
    popularityScore: 910,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_030',
    name: 'Soi70 Gulshan',
    location: { type: 'Point', coordinates: [90.4140, 23.7785] },
    address: {
      formatted: 'Navana Rowshan, Gulshan Avenue, Gulshan 1, Dhaka 1212',
      street: 'Gulshan Avenue',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1212',
    },
    categories: ['restaurant', 'thai_restaurant'],
    cuisine: ['thai', 'asian'],
    priceLevel: 3,
    rating: 4.5,
    totalRatings: 1700,
    phone: '+880 1819-223388',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:30 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&q=80',
    tags: ['thai', 'pad krapow', 'tom yum', 'gulshan', 'asian', 'spicy thai'],
    reviews: [
      { author: 'Faisal Noor', rating: 5, text: 'Truly spicy, authentic Bangkok street flavors right in Gulshan 1!' },
      { author: 'Tahsin Ara', rating: 4, text: 'Pad Thai noodles have the perfect wok-hei smokiness.' },
    ],
    popularityScore: 740,
    isFeatured: false,
    source: 'seed',
  },

  // ── OLD DHAKA (PURAN DHAKA) ────────────────────────────────────
  {
    googlePlaceId: 'seed_dhaka_002',
    name: 'Haji Mohammad Ali Biryani Hotel',
    location: { type: 'Point', coordinates: [90.4074, 23.7230] },
    address: {
      formatted: 'Nazira Bazar, Old Dhaka, Dhaka 1100',
      street: 'Nazira Bazar',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1100',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 1,
    rating: 4.8,
    totalRatings: 6200,
    phone: '+880 1919-345678',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:00 AM – 9:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&q=80',
    tags: ['haji biryani', 'old dhaka', 'traditional', 'cheap', 'iconic', 'mutton biryani'],
    reviews: [
      { author: 'Karim Uddin', rating: 5, text: 'Serving legendary biryani for generations in jackfruit leaf plates!' },
      { author: 'Sadia Islam', rating: 4, text: 'Authentic Old Dhaka flavors. Mustard oil aroma is extraordinary.' },
    ],
    popularityScore: 1100,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_003',
    name: 'Star Kabab & Restaurant',
    location: { type: 'Point', coordinates: [90.4060, 23.7180] },
    address: {
      formatted: '51 North Brook Hall Rd, Old Dhaka, Dhaka 1100',
      street: 'North Brook Hall Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1100',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'kabab'],
    priceLevel: 1,
    rating: 4.5,
    totalRatings: 4100,
    phone: '+880 1712-456789',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 10:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    tags: ['kabab', 'tikka', 'old dhaka', 'cheap', 'street food', 'grilled', 'boti kabab'],
    reviews: [
      { author: 'Farhan Hossain', rating: 5, text: 'Best kabab in Dhaka. Smoky, juicy, and incredibly cheap.' },
      { author: 'Mitu Begum', rating: 4, text: 'Classic Old Dhaka kabab experience. Come early, it gets packed.' },
    ],
    popularityScore: 950,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_036',
    name: 'Grand Nawab',
    location: { type: 'Point', coordinates: [90.4085, 23.7225] },
    address: {
      formatted: 'Kazi Alauddin Road, Nazira Bazar, Old Dhaka 1100',
      street: 'Kazi Alauddin Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1100',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 2,
    rating: 4.7,
    totalRatings: 4300,
    phone: '+880 1744-889900',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    tags: ['kacchi biryani', 'shahi morog polao', 'borhani', 'old dhaka', 'nazira bazar', 'nawab'],
    reviews: [
      { author: 'Shakil Mahmud', rating: 5, text: 'Royal Mughlai flavors. The Shahi Morog Polao is packed with aroma.' },
      { author: 'Farzana Yesmin', rating: 5, text: 'Kacchi biryani served with real saffron and rich spices. Top 3 in Dhaka.' },
    ],
    popularityScore: 1050,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_037',
    name: 'Al-Razzak Hotel',
    location: { type: 'Point', coordinates: [90.4045, 23.7195] },
    address: {
      formatted: '29 Bangshal Road, Old Dhaka 1100',
      street: 'Bangshal Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1100',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'kabab', 'biryani'],
    priceLevel: 1,
    rating: 4.6,
    totalRatings: 5400,
    phone: '+880 1819-332211',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 6:00 AM – 1:00 AM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    tags: ['glace mutton', 'tehari', 'sheekh kabab', 'bakarkhani', 'old dhaka', 'iconic'],
    reviews: [
      { author: 'Kamrul Hasan', rating: 5, text: 'Their Glace Mutton and hot tandoori roti at midnight is historic.' },
      { author: 'Munira Khatun', rating: 4, text: 'Authentic heritage taste of Old Dhaka. Highly recommended.' },
    ],
    popularityScore: 1020,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_038',
    name: 'Nirob Hotel',
    location: { type: 'Point', coordinates: [90.4025, 23.7255] },
    address: {
      formatted: '113/2 Nazimuddin Road, Old Dhaka 1100',
      street: 'Nazimuddin Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1100',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'seafood'],
    priceLevel: 1,
    rating: 4.7,
    totalRatings: 3900,
    phone: '+880 1712-990011',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 7:00 AM – 11:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    tags: ['bhorta', 'hilsha fish', 'bangladeshi', 'traditional', 'cheap', 'old dhaka', 'fish curry'],
    reviews: [
      { author: 'Zahidul Islam', rating: 5, text: '30+ varieties of traditional bhortas with steaming hot rice and hilsha curry!' },
      { author: 'Laboni Das', rating: 5, text: 'Unbeatable home-cooked authentic Bengali taste in Puran Dhaka.' },
    ],
    popularityScore: 980,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_039',
    name: 'Beauty Lassi & Faluda',
    location: { type: 'Point', coordinates: [90.4070, 23.7228] },
    address: {
      formatted: '30/1 Johnson Road, Nazira Bazar, Old Dhaka 1100',
      street: 'Johnson Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1100',
    },
    categories: ['cafe', 'dessert_shop'],
    cuisine: ['dessert', 'bangladeshi'],
    priceLevel: 1,
    rating: 4.8,
    totalRatings: 6700,
    phone: '+880 1817-554433',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 9:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80',
    tags: ['lassi', 'faluda', 'lemonade', 'old dhaka', 'sweet', 'century old', 'legendary'],
    reviews: [
      { author: 'Abir Chowdhury', rating: 5, text: '100+ year old heritage spot. The special faluda with kulfi is unmatched!' },
      { author: 'Nusrat Noor', rating: 5, text: 'Best sweet lassi in Bangladesh. Refreshing and nostalgic.' },
    ],
    popularityScore: 1150,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_040',
    name: 'Bismillah Kabab Ghar',
    location: { type: 'Point', coordinates: [90.4078, 23.7220] },
    address: {
      formatted: 'Nazira Bazar, Old Dhaka 1100',
      street: 'Nazira Bazar',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1100',
    },
    categories: ['restaurant', 'street_food'],
    cuisine: ['kabab', 'bangladeshi'],
    priceLevel: 1,
    rating: 4.6,
    totalRatings: 4800,
    phone: '+880 1911-224466',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 4:00 PM – 1:00 AM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    tags: ['beef chaap', 'luchi', 'sheekh kabab', 'brain masala', 'old dhaka street food'],
    reviews: [
      { author: 'Mamunur Rashid', rating: 5, text: 'Crispy fried beef chaap with hot fluffy luchis is heavenly.' },
      { author: 'Sultana Razia', rating: 4, text: 'Authentic late-night Old Dhaka street food culture.' },
    ],
    popularityScore: 920,
    isFeatured: false,
    source: 'seed',
  },

  // ── UTTARA ─────────────────────────────────────────────────────
  {
    googlePlaceId: 'seed_dhaka_019',
    name: 'Street Oven Uttara',
    location: { type: 'Point', coordinates: [90.3880, 23.8720] },
    address: {
      formatted: 'Gareeb-e-Nawaz Avenue, Sector 11, Uttara, Dhaka 1230',
      street: 'Gareeb-e-Nawaz Avenue',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1230',
    },
    categories: ['restaurant', 'pizza_restaurant', 'italian_restaurant'],
    cuisine: ['pizza', 'italian'],
    priceLevel: 2,
    rating: 4.6,
    totalRatings: 2800,
    phone: '+880 1766-332211',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
    tags: ['pizza', 'wood fired pizza', 'uttara', 'italian', 'pasta', 'thin crust', 'sourdough'],
    reviews: [
      { author: 'Tanvir Hossain', rating: 5, text: 'Best wood-fired pizza in Uttara! The crust has amazing char and flavor.' },
      { author: 'Shabnam Faria', rating: 5, text: 'Great cheesy garlic bread and rustic margherita pizza.' },
    ],
    popularityScore: 880,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_020',
    name: 'Madchef Uttara',
    location: { type: 'Point', coordinates: [90.3995, 23.8640] },
    address: {
      formatted: 'Rabindra Sarani, Sector 3, Uttara, Dhaka 1230',
      street: 'Rabindra Sarani',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1230',
    },
    categories: ['restaurant', 'burger_restaurant'],
    cuisine: ['burger', 'american'],
    priceLevel: 2,
    rating: 4.5,
    totalRatings: 3100,
    phone: '+880 1844-556677',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:30 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
    tags: ['burger', 'gourmet burger', 'uttara', 'loaded fries', 'milkshake', 'fast food'],
    reviews: [
      { author: 'Nayeem Hasan', rating: 5, text: 'Madchef in Uttara never disappoints. The Naga burger is fire!' },
      { author: 'Rumana Islam', rating: 4, text: 'Great outdoor seating vibe and delicious cheesy burgers.' },
    ],
    popularityScore: 840,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_021',
    name: 'Kacchi Ghor Uttara',
    location: { type: 'Point', coordinates: [90.4010, 23.8685] },
    address: {
      formatted: 'House 14, Road 1, Sector 7, Uttara, Dhaka 1230',
      street: 'Road 1, Sector 7',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1230',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 2,
    rating: 4.6,
    totalRatings: 2500,
    phone: '+880 1722-113355',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    tags: ['kacchi biryani', 'uttara', 'mutton', 'chaler biryani', 'family dining'],
    reviews: [
      { author: 'Tawfiq Omar', rating: 5, text: 'Generous meat portions, soft potatoes and aromatic basmati rice.' },
      { author: 'Sayeeda Begum', rating: 4, text: 'Top kacchi destination for Uttara residents. Great borhani.' },
    ],
    popularityScore: 820,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_022',
    name: 'Gloria Jean\'s Coffees Uttara',
    location: { type: 'Point', coordinates: [90.3980, 23.8625] },
    address: {
      formatted: 'Jashimuddin Avenue, Sector 3, Uttara, Dhaka 1230',
      street: 'Jashimuddin Avenue',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1230',
    },
    categories: ['cafe', 'coffee_shop'],
    cuisine: ['coffee', 'breakfast', 'dessert'],
    priceLevel: 3,
    rating: 4.5,
    totalRatings: 3300,
    phone: '+880 1888-990022',
    website: 'https://gloriajeanscoffeesbd.com',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 8:00 AM – 11:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80',
    tags: ['coffee', 'latte', 'chiller', 'uttara', 'work cafe', 'cheesecake', 'breakfast'],
    reviews: [
      { author: 'Arif Billah', rating: 5, text: 'Spacious 2-story cafe, great for remote work and meetings in Uttara.' },
      { author: 'Farah Diba', rating: 4, text: 'Signature chocolate chillers and warm apple pie are fantastic.' },
    ],
    popularityScore: 890,
    isFeatured: false,
    source: 'seed',
  },

  // ── KHILGAON & BAILY ROAD ──────────────────────────────────────
  {
    googlePlaceId: 'seed_dhaka_041',
    name: 'Salam\'s Kitchen Baily Road',
    location: { type: 'Point', coordinates: [90.4095, 23.7410] },
    address: {
      formatted: '12 New Baily Road, Dhaka 1000',
      street: 'New Baily Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1000',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 2,
    rating: 4.7,
    totalRatings: 5100,
    phone: '+880 1711-667788',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 10:30 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    tags: ['kacchi biryani', 'baily road', 'shahi biryani', 'mutton', 'borhani', 'legendary'],
    reviews: [
      { author: 'Mahfuzur Rahman', rating: 5, text: 'Baily Road food walk must-visit! Incredibly tender mutton and buttery potatoes.' },
      { author: 'Jannatul Ferdous', rating: 5, text: 'Always freshly prepared and the spiced borhani is divine.' },
    ],
    popularityScore: 1080,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_042',
    name: 'Alfresco Khilgaon',
    location: { type: 'Point', coordinates: [90.4215, 23.7540] },
    address: {
      formatted: 'Shahid Baki Road, Taltola, Khilgaon, Dhaka 1219',
      street: 'Shahid Baki Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1219',
    },
    categories: ['restaurant', 'pizza_restaurant', 'italian_restaurant'],
    cuisine: ['pizza', 'italian'],
    priceLevel: 2,
    rating: 4.5,
    totalRatings: 3400,
    phone: '+880 1855-443322',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
    tags: ['pizza', 'khilgaon', 'pasta', 'italian', 'thin crust', 'cheese burst', 'budget friendly'],
    reviews: [
      { author: 'Mehedi Maruf', rating: 5, text: 'Best pizza spot on the Khilgaon food street! Loaded with toppings.' },
      { author: 'Mithila Roy', rating: 4, text: 'Great thin crust pizza and creamy Alfredo pasta at student-friendly prices.' },
    ],
    popularityScore: 890,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_043',
    name: 'Tradition BD Khilgaon',
    location: { type: 'Point', coordinates: [90.4230, 23.7555] },
    address: {
      formatted: 'Taltola Market, Khilgaon, Dhaka 1219',
      street: 'Taltola Market',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1219',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'kabab'],
    priceLevel: 1,
    rating: 4.6,
    totalRatings: 4200,
    phone: '+880 1711-223399',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 3:00 PM – 12:00 AM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    tags: ['chaap', 'luchi', 'sheekh kabab', 'khilgaon', 'street food', 'khilgaon food street'],
    reviews: [
      { author: 'Habibul Bashar', rating: 5, text: 'Famous beef chaap in Khilgaon. Crunchy, spicy and mouth-watering.' },
      { author: 'Fatima Zohra', rating: 4, text: 'Unmissable street food experience when visiting Khilgaon.' },
    ],
    popularityScore: 910,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_044',
    name: 'Coffee Buzz Baily Road',
    location: { type: 'Point', coordinates: [90.4102, 23.7425] },
    address: {
      formatted: 'Baily Fiesta, New Baily Road, Dhaka 1000',
      street: 'New Baily Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1000',
    },
    categories: ['cafe', 'dessert_shop'],
    cuisine: ['coffee', 'breakfast', 'dessert'],
    priceLevel: 2,
    rating: 4.5,
    totalRatings: 2100,
    phone: '+880 1933-221100',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 9:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    tags: ['coffee', 'waffles', 'crepes', 'baily road', 'desserts', 'hangout'],
    reviews: [
      { author: 'Sadia Afroz', rating: 5, text: 'Nutella waffles and hazelnut cappuccino are a match made in heaven!' },
      { author: 'Tarek Jamil', rating: 4, text: 'Lively spot after theater shows on Baily Road.' },
    ],
    popularityScore: 780,
    isFeatured: false,
    source: 'seed',
  },

  // ── MIRPUR & ELEPHANT ROAD ─────────────────────────────────────
  {
    googlePlaceId: 'seed_dhaka_009',
    name: 'Panshi Restaurant Elephant Road',
    location: { type: 'Point', coordinates: [90.3900, 23.7530] },
    address: {
      formatted: '2 Elephant Road, Dhaka 1205',
      street: 'Elephant Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1205',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'seafood'],
    priceLevel: 2,
    rating: 4.3,
    totalRatings: 3900,
    phone: '+880 1600-012345',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    tags: ['bangladeshi', 'sylheti', 'hilsa', 'fish curry', 'dal', 'family', 'affordable'],
    reviews: [
      { author: 'Shahin Mia', rating: 4, text: 'Traditional Bangladeshi food. Their hilsa curry is to die for!' },
      { author: 'Fatema Begum', rating: 4, text: 'Huge portions, great value. Fish curry is delicious.' },
    ],
    popularityScore: 750,
    isFeatured: false,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_045',
    name: 'Kacchi Khadok Mirpur',
    location: { type: 'Point', coordinates: [90.3680, 23.8070] },
    address: {
      formatted: 'Mirpur 10 Roundabout, Mirpur, Dhaka 1216',
      street: 'Mirpur 10 Roundabout',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1216',
    },
    categories: ['restaurant', 'bangladeshi_restaurant'],
    cuisine: ['bangladeshi', 'biryani'],
    priceLevel: 2,
    rating: 4.6,
    totalRatings: 4400,
    phone: '+880 1733-998877',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 12:00 PM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    tags: ['kacchi biryani', 'mirpur', 'mutton', 'borhani', 'shahi biryani', 'affordable'],
    reviews: [
      { author: 'Rasel Ahmed', rating: 5, text: 'The undisputed king of Kacchi in Mirpur! Tender mutton and tasty aloo.' },
      { author: 'Shahana Akter', rating: 4, text: 'Huge crowd always. The basmati kacchi is totally worth the queue.' },
    ],
    popularityScore: 970,
    isFeatured: true,
    source: 'seed',
  },
  {
    googlePlaceId: 'seed_dhaka_046',
    name: 'BFC (Best Fried Chicken) Mirpur',
    location: { type: 'Point', coordinates: [90.3525, 23.7960] },
    address: {
      formatted: 'Plot 3, Block D, Mirpur 1, Dhaka 1216',
      street: 'Block D, Mirpur 1',
      city: 'Dhaka',
      state: 'Dhaka Division',
      country: 'Bangladesh',
      postalCode: '1216',
    },
    categories: ['restaurant', 'fast_food', 'chicken_restaurant'],
    cuisine: ['chicken', 'burger', 'fast food'],
    priceLevel: 2,
    rating: 4.4,
    totalRatings: 3500,
    phone: '+880 1711-445588',
    openingHours: {
      openNow: true,
      weekdayText: ['Daily: 11:00 AM – 11:00 PM'],
    },
    primaryPhoto: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80',
    tags: ['crispy chicken', 'fried chicken', 'burger', 'mirpur', 'fast food', 'chips'],
    reviews: [
      { author: 'Monirul Islam', rating: 5, text: 'Crispiest fried chicken in Dhaka! Spicy masala sprinkle is legendary.' },
      { author: 'Dilruba Yasmin', rating: 4, text: 'Family favorite fried chicken for decades.' },
    ],
    popularityScore: 820,
    isFeatured: false,
    source: 'seed',
  },
];

const seed = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/cravecompass';
    console.log('Connecting to MongoDB at:', mongoUri);
    await mongoose.connect(mongoUri);
    console.log('✅ MongoDB connected');

    // Ensure database indexes exist (2dsphere + text)
    await Place.syncIndexes();
    console.log('✅ GeoJSON 2dsphere and Full-Text indexes synchronized');

    // Clean up old seed records
    const deleteResult = await Place.deleteMany({ source: 'seed' });
    console.log(`🗑️  Cleared ${deleteResult.deletedCount} existing seed records`);

    // Insert all Dhaka restaurants
    const inserted = await Place.insertMany(SEED_PLACES);
    console.log(`\n🌱 Successfully seeded ${inserted.length} real Dhaka restaurants!`);

    // Print breakdown by cuisine
    const cuisineCounts = {};
    inserted.forEach((p) => {
      (p.cuisine || []).forEach((c) => {
        cuisineCounts[c] = (cuisineCounts[c] || 0) + 1;
      });
    });

    console.log('\n📊 Cuisine Coverage:');
    Object.entries(cuisineCounts)
      .sort((a, b) => b[1] - a[1])
      .forEach(([cuisine, count]) => {
        console.log(`   • ${cuisine.padEnd(16)} : ${count} restaurants`);
      });

    console.log('\n📍 Sample Seeded Restaurants:');
    inserted.slice(0, 10).forEach((p, i) => {
      console.log(`   ${i + 1}. ${p.name.padEnd(30)} — ${p.address.formatted}`);
    });
    console.log(`   ... and ${inserted.length - 10} more!`);

    await mongoose.disconnect();
    console.log('\n✅ Database is primed and ready for deployment!');
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
};

seed();
